//! Runs code generated by planner.

use thiserror::Error;

pub mod expression;
pub mod operator;
pub mod query_result;
pub mod seq_scan;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error(transparent)]
    Storage(#[from] crate::storage::Error),

    #[error("division by zero: {0} / {1}")]
    DivisionByZero(i64, i64),
}
