//! Runs code generated by planner.

use thiserror::Error;

use crate::{
    database::WriteDbTx,
    sql::parser::statement::Expression,
    vm::{
        planner::ExecutionPlan,
        query_result::{QueryResult, RowIterator},
    },
};

pub mod ddl;
pub mod dml;
pub mod expression;
pub mod operator;
pub mod planner;
pub mod query_result;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("division by zero: {0} / {1}")]
    DivisionByZero(i64, i64),

    #[error("unsupported expression: {0}")]
    Unsupported(Expression),

    #[error(transparent)]
    StorageError(#[from] crate::storage::Error),

    #[error(transparent)]
    SqlError(#[from] crate::sql::Error),

    #[error(transparent)]
    AnalyzerError(#[from] crate::sql::analyzer::Error),

    #[error(transparent)]
    SchemaError(#[from] crate::sql::schema::Error),
}

pub fn execute_read<'tx>(plan: ExecutionPlan<'tx>) -> Result<QueryResult<'tx>> {
    match plan {
        ExecutionPlan::Select(operator) => Ok(QueryResult::Rows(RowIterator::new(operator))),
        _ => unreachable!(),
    }
}

pub fn execute_write<'tx, Tx: WriteDbTx>(
    tx: &'tx Tx,
    plan: ExecutionPlan<'tx>,
) -> Result<QueryResult<'tx>> {
    match plan {
        ExecutionPlan::Select(operator) => Ok(QueryResult::Rows(RowIterator::new(operator))),

        ExecutionPlan::Create(create) => ddl::create(tx, create),

        ExecutionPlan::Insert {
            into,
            columns,
            values,
        } => dml::insert(tx, into, columns, values),
        _ => todo!(),
    }
}
