//! Runs code generated by planner.

use thiserror::Error;

use crate::{
    database::DatabaseTransaction,
    sql::parser::statement::Expression,
    vm::{
        planner::ExecutionPlan,
        query_result::{QueryResult, RowIterator},
    },
};

pub mod ddl;
pub mod dml;
pub mod expression;
pub mod operator;
pub mod planner;
pub mod query_result;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("division by zero: {0} / {1}")]
    DivisionByZero(i64, i64),

    #[error("transaction is in read only mode.")]
    ReadOnly,

    #[error("unsupported expression: {0}")]
    Unsupported(Expression),

    #[error(transparent)]
    StorageError(#[from] crate::storage::Error),

    #[error(transparent)]
    SqlError(#[from] crate::sql::Error),

    #[error(transparent)]
    AnalyzerError(#[from] crate::sql::analyzer::Error),

    #[error(transparent)]
    SchemaError(#[from] crate::sql::schema::Error),
}

pub fn execute<'tx>(
    tx: &DatabaseTransaction<'tx>,
    plan: ExecutionPlan<'tx>,
) -> Result<QueryResult<'tx>> {
    match plan {
        ExecutionPlan::Query(operator) => Ok(QueryResult::Rows(RowIterator::new(operator))),

        ExecutionPlan::Create(create) => ddl::create(tx, create),

        _ => todo!(),
    }
}
