//! Runs code generated by planner.

use thiserror::Error;

use crate::{
    database::DatabaseTransaction,
    sql::parser::statement::Expression,
    vm::{
        planner::ExecutionPlan,
        query_result::{QueryResult, RecordIterator},
    },
};

pub mod ddl;
pub mod dml;
pub mod expression;
pub mod operator;
pub mod planner;
pub mod query_result;

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Debug, Error)]
pub enum Error {
    #[error("division by zero: {0} / {1}")]
    DivisionByZero(i64, i64),

    #[error("transaction is in read only mode.")]
    ReadOnly,

    #[error("unsupported expression: {0}")]
    Unsupported(Expression),

    #[error("data was currupted.")]
    Corrupted,

    #[error(transparent)]
    StorageError(#[from] crate::storage::Error),

    #[error(transparent)]
    SqlError(#[from] crate::sql::Error),

    #[error(transparent)]
    AnalyzerError(#[from] crate::sql::analyzer::Error),

    #[error(transparent)]
    SchemaError(#[from] crate::sql::schema::Error),
}

pub fn execute<'a>(
    tx: &'a DatabaseTransaction,
    plan: ExecutionPlan<'a>,
) -> Result<QueryResult<'a>> {
    match plan {
        ExecutionPlan::Select(operator) => {
            tx.acquire_read()?;
            Ok(QueryResult::Records(RecordIterator::new(Box::new(
                operator,
            ))))
        }

        ExecutionPlan::Delete(operator) => {
            tx.acquire_write()?;
            Ok(QueryResult::Records(RecordIterator::new(Box::new(
                operator,
            ))))
        }

        ExecutionPlan::Insert(insert) => {
            tx.acquire_write()?;
            let is_returning = insert.is_returning;
            let row_iterator = RecordIterator::new(Box::new(insert));
            if is_returning {
                Ok(QueryResult::Records(row_iterator))
            } else {
                let mut inserted = 0;
                for row_result in row_iterator {
                    let _ = row_result?;
                    inserted += 1;
                }
                Ok(QueryResult::RecordsAffected(inserted))
            }
        }

        ExecutionPlan::Update(update) => {
            tx.acquire_write()?;
            let is_returning = update.is_returning;
            let row_iterator = RecordIterator::new(Box::new(update));
            if is_returning {
                Ok(QueryResult::Records(row_iterator))
            } else {
                let mut updated = 0;
                for row_result in row_iterator {
                    let _ = row_result?;
                    updated += 1;
                }
                Ok(QueryResult::RecordsAffected(updated))
            }
        }

        ExecutionPlan::Create(create) => {
            tx.acquire_write()?;
            ddl::create(tx, create)
        }

        _ => todo!(),
    }
}
